### ISSUE TITLE
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value: assert(parentSymbol)

### ISSUE THREAD

**Issue by jsalvata** [Gerrit0/typedoc-plugin-missing-exports#3]
Steps to reproduce:

Download [typedoc-assertion-error.zip](https://github.com/Gerrit0/typedoc-plugin-missing-exports/files/7444591/typedoc-assertion-error.zip)

```
$ unzip typedoc-assertion-error.zip
$ cd typedoc-assertion-error
$ npm ci
$ npx typedoc
```

Error:
```
TypeDoc exiting with unexpected error:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(parentSymbol)

    at isInherited (.../typedoc-assertion-error/node_modules/typedoc/dist/lib/converter/symbols.js:531:5)
    at Object.convertProperty (.../typedoc-assertion-error/node_modules/typedoc/dist/lib/converter/symbols.js:319:9)
    at convertSymbol (.../typedoc-assertion-error/node_modules/typedoc/dist/lib/converter/symbols.js:120:88)
    at Converter.convertSymbol (.../typedoc-assertion-error/node_modules/typedoc/dist/lib/converter/converter.js:45:37)
    at onResolveBegin (.../typedoc-assertion-error/node_modules/typedoc-plugin-missing-exports/index.js:44:43)
    at triggerEvents (.../typedoc-assertion-error/node_modules/typedoc/dist/lib/utils/events.js:191:43)
    at triggerApi (.../typedoc-assertion-error/node_modules/typedoc/dist/lib/utils/events.js:167:13)
    at eventsApi (.../typedoc-assertion-error/node_modules/typedoc/dist/lib/utils/events.js:60:18)
    at Converter.trigger (.../typedoc-assertion-error/node_modules/typedoc/dist/lib/utils/events.js:389:13)
    at Converter.resolve (.../typedoc-assertion-error/node_modules/typedoc/dist/lib/converter/converter.js:199:14) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

**Comment by jsalvata** [comment]
Note: I used `underscore` as a stub for any module without types. It doesn't make sense to import types from there, I know, but I have a few like those in the code, I suspect from migrating from Flow using automated tools.

**Comment by MasterOdin** [comment]
Running into this same issue when trying to generate docs for a monorepo: https://github.com/bishopcais/io

Running with the verbose flag does not give me a lead on what's going on:

```
$ typedoc --logLevel Verbose
Info: Loaded plugin typedoc-plugin-missing-exports
Debug: Using TypeScript 4.4.3 from ./node_modules/typescript/lib
Debug: Converting with 5 programs 5 entry points
Debug: Finished getting entry points in 10999ms
Debug: Begin readme search at /Users/mpeveler/code/github/bishopcais
Debug: Missing converter for symbol: T with flag TypeParameter
Debug: Missing converter for symbol: K with flag TypeParameter
Debug: Missing converter for symbol: U with flag TypeParameter
Debug: Missing converter for symbol: U with flag TypeParameter
Debug: Missing converter for symbol: P with flag TypeParameter
Debug: Missing converter for symbol: R with flag TypeParameter
TypeDoc exiting with unexpected error:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(parentSymbol)

    at isInherited (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc/dist/lib/converter/symbols.js:531:5)
    at Object.convertProperty (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc/dist/lib/converter/symbols.js:319:9)
    at convertSymbol (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc/dist/lib/converter/symbols.js:120:88)
    at Converter.convertSymbol (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc/dist/lib/converter/converter.js:45:37)
    at onResolveBegin (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc-plugin-missing-exports/index.js:44:43)
    at triggerEvents (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc/dist/lib/utils/events.js:191:43)
    at triggerApi (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc/dist/lib/utils/events.js:167:13)
    at eventsApi (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc/dist/lib/utils/events.js:60:18)
    at Converter.trigger (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc/dist/lib/utils/events.js:389:13)
    at Converter.resolve (/Users/mpeveler/code/github/bishopcais/io/node_modules/typedoc/dist/lib/converter/converter.js:199:14) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

Using the latest typedoc version.

**Comment by Gerrit0** [comment]
The test case in the OP works now with v0.22.4 of this plugin. It might fix your issue as well @MasterOdin. If it doesn't, please open a new issue.
