### ISSUE TITLE
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:    assert(parentSymbol)

### ISSUE THREAD

**Issue by matteobruni** [Gerrit0/typedoc-plugin-missing-exports#4]
I've checked #3, I've the latest version of `typedoc` and this plugin (`0.22.8` and `0.22.4`) but the error was still returned

``` shell
Info: Loaded plugin typedoc-plugin-missing-exports
TypeDoc exiting with unexpected error:
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert(parentSymbol)

    at isInherited (***/tsparticles-v1/engine/node_modules/typedoc/dist/lib/converter/symbols.js:531:5)
    at Object.convertProperty (***/tsparticles-v1/engine/node_modules/typedoc/dist/lib/converter/symbols.js:319:9)
    at convertSymbol (***/tsparticles-v1/engine/node_modules/typedoc/dist/lib/converter/symbols.js:120:88)
    at Converter.convertSymbol (***/tsparticles-v1/engine/node_modules/typedoc/dist/lib/converter/converter.js:45:37)
    at onResolveBegin (***/tsparticles-v1/engine/node_modules/typedoc-plugin-missing-exports/index.js:45:47)
    at triggerEvents (***/tsparticles-v1/engine/node_modules/typedoc/dist/lib/utils/events.js:191:43)
    at triggerApi (***/tsparticles-v1/engine/node_modules/typedoc/dist/lib/utils/events.js:167:13)
    at eventsApi (***/tsparticles-v1/engine/node_modules/typedoc/dist/lib/utils/events.js:60:18)
    at Converter.trigger (***/tsparticles-v1/engine/node_modules/typedoc/dist/lib/utils/events.js:389:13)
    at Converter.resolve (***/tsparticles-v1/engine/node_modules/typedoc/dist/lib/converter/converter.js:199:14) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
error Command failed with exit code 6.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

The repository is a monorepo maintained with `lerna`.

You can see the repo [here](https://github.com/matteobruni/tsparticles/tree/v1), the `engine` folder is the one that uses `typedoc` and this plugin.

**Comment by Gerrit0** [comment]
As a person who just wants a simple repo... Man I really hate monorepos... having been on the other side... they're so very nice though... Will take a look Sunday most likely

**Comment by Gerrit0** [comment]
Later than I wanted, but... I still hate monorepos. How am I supposed to install stuff? I just ran "yarn" in the root and it did a thing, but the v1 branch you linked doesn't have this plugin installed, and it doesn't seem to like when I add the package into the appropriate package.json and reinstall (from either the engine folder or root)

If you can set up a branch I can check out and install on that directly reproduces this, that would be great.

**Comment by matteobruni** [comment]
I tested this with 0.22.9 and it's working. I close this since it's not giving errors anymore.
