### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Missing symbol when converting import type node

### ISSUE THREAD

**Issue by D4nte** [Gerrit0/typedoc-plugin-missing-exports#6]
At this repo/commit: https://github.com/status-im/js-waku/commit/c9a32b12719c1fb7a94568fa815ec6463a67df53

I am getting the error:

```
> typedoc --excludeInternal --listInvalidSymbolLinks --exclude **/*.spec.ts --out build/docs src/

Info: Loaded plugin typedoc-plugin-missing-exports
Info: Loaded plugin typedoc-plugin-no-inherit
TypeDoc exiting with unexpected error:
AssertionError [ERR_ASSERTION]: Missing symbol when converting import type node
    at Object.convert (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/types.js:215:9)
    at convertType (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/types.js:70:30)
    at Converter.convertType (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/converter.js:56:40)
    at Object.convertTypeAlias (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/symbols.js:174:45)
    at convertSymbol (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/symbols.js:123:88)
    at Object.convertAlias (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/symbols.js:421:9)
    at convertSymbol (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/symbols.js:123:88)
    at convertSymbols (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/symbols.js:129:9)
    at Object.convertNamespace (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/symbols.js:161:5)
    at convertSymbol (/home/froyer/src/status-im/js-waku/node_modules/typedoc/dist/lib/converter/symbols.js:123:88) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

**Comment by Gerrit0** [comment]
I believe this is likely a typedoc problem, should be reproducible with something like this:
```ts
export class Foo {
  // "foo" must not have types
  foo: import("foo").Foo
}
```

**Comment by Gerrit0** [comment]
My note from last year hasn't let me reproduce this locally with TypeScript 4.7.2, TypeDoc 0.23.1 - if you can submit a PR with a repro to https://github.com/TypeStrong/typedoc-repros I can take a closer look at some point
