### ISSUE TITLE
AssertionError [ERR_ASSERTION]: No parent symbol found

### ISSUE THREAD

**Issue by krjj** [Gerrit0/typedoc-plugin-missing-exports#7]
code - 

```
import { sum } from "lodash-es";

function sayBye(message: string): ReturnType<typeof sum> {
  return sum([1, 1]);
}

export { sayBye };

```

tsconfig.json - 
```
{
  "include": ["."],
  "compilerOptions": {
    "target": "ES2021",
    "module": "ESNext",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "strict": true,
    "sourceMap": true
  },
  "typedocOptions": {
    "entryPoints": ["index.ts"],
    "out": "docs",
    "json": "docs/out.json",
    "plugin": ["typedoc-plugin-missing-exports"],
    "pretty": true
  }
}
```

I am getting this error :  
This happens when `ReturnType` is used in the code.

```
Info: Loaded plugin typedoc-plugin-missing-exports
TypeDoc exiting with unexpected error:
AssertionError [ERR_ASSERTION]: No parent symbol found for sum in <internal>
    at isInherited (/Users/k/p/tal/node_modules/typedoc/dist/lib/converter/symbols.js:534:5)
    at Object.convertFunctionOrMethod (/Users/k/p/tal/node_modules/typedoc/dist/lib/converter/symbols.js:210:9)
    at convertSymbol (/Users/k/p/tal/node_modules/typedoc/dist/lib/converter/symbols.js:123:88)
    at Converter.convertSymbol (/Users/k/p/tal/node_modules/typedoc/dist/lib/converter/converter.js:45:37)
    at onResolveBegin (/Users/k/p/tal/node_modules/typedoc-plugin-missing-exports/index.js:45:47)
    at triggerEvents (/Users/k/p/tal/node_modules/typedoc/dist/lib/utils/events.js:191:43)
    at triggerApi (/Users/k/p/tal/node_modules/typedoc/dist/lib/utils/events.js:167:13)
    at eventsApi (/Users/k/p/tal/node_modules/typedoc/dist/lib/utils/events.js:60:18)
    at Converter.trigger (/Users/k/p/tal/node_modules/typedoc/dist/lib/utils/events.js:389:13)
    at Converter.resolve (/Users/k/p/tal/node_modules/typedoc/dist/lib/converter/converter.js:199:14) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: true,
  operator: '=='
}
```

**Comment by Gerrit0** [comment]
I can't seem to reproduce this with TypeScript 4.7.4, TypeDoc 0.23.1 if you could send a PR to https://github.com/TypeStrong/typedoc-repros with a reproduction, that would be great!
